# Generated by Django 3.2 on 2023-04-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Биография'),
            preserve_default=False,
        ),
    ]
