# Generated by Django 3.2 on 2023-04-19 13:30

import api_yamdb.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, validators=[api_yamdb.validators.validate_slug], verbose_name='Адрес'),
        ),
    ]
