# Generated by Django 3.2 on 2023-04-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_title_year'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='title_one_review',
        ),
    ]
